const aqidah = [
{ no: 1, judul: 'كتاب التوحيد', tema: 'aqidah', penerbit: 'مكتبة الهدي المحمدي', pembuat: 'صالح بن فوزان بن عبد الله الفوزان', totalBuku: 1, sinopsis: '' },
  { no: 2, judul: 'خذ عقيدتك', tema: 'aqidah', penerbit: 'مكتبة الشافعية', pembuat: 'محمد بن جميل زينو', totalBuku: 2, sinopsis: '' },
  { no: 3, judul: 'نبذة في العقيدة الاسلامية', tema: 'aqidah', penerbit: 'مؤسسة ابن العثيمين', pembuat: 'محمد بن صالح بن محمد العثيمين', totalBuku: 2, sinopsis: '' },
  { no: 4, judul: 'رسالة في التوحيد', tema: 'aqidah', penerbit: '-', pembuat: 'عبد الله بن محمد بن زاحم', totalBuku: 1, sinopsis: '' },
  { no: 5, judul: 'اعلام السنة المنشورة', tema: 'aqidah', penerbit: 'دار الفرقان', pembuat: 'حافظ بن احمد الحكمي', totalBuku: 3, sinopsis: '' },
  { no: 6, judul: 'المعتقد الصحيح', tema: 'aqidah', penerbit: 'دار الفرقان', pembuat: 'عبد السلام بن برجس ', totalBuku: 1, sinopsis: '' },
  { no: 7, judul: 'عقيدة التوحيد', tema: 'aqidah', penerbit: ' دار أعلام السنة', pembuat: 'صالح بن فوزان بن عبد الله الفوزان', totalBuku: 2, sinopsis: '' },
  { no: 8, judul: 'شرح لمعة الاعتقاد', tema: 'aqidah', penerbit: 'دار ابن الجوزي', pembuat: 'عبد الله بن احمد بن قدامة المقدسي', totalBuku: 2, sinopsis: '' },
  { no: 9, judul: 'جامع شروح الستة الأصول', tema: 'aqidah', penerbit: 'دار ابن الجوزي', pembuat: 'محمد بن عبد الوهاب بن سليمان التميمي', totalBuku: 2, sinopsis: '' },
  { no: 10, judul: 'شرح الاصول الستة', tema: 'aqidah', penerbit: 'دار عمر بن الخطاب', pembuat: 'محمد بن عبد الوهاب بن سليمان التميمي', totalBuku: 2, sinopsis: '' },
  { no: 11, judul: 'الطيب الجني على شرح السنة', tema: 'aqidah', penerbit: 'الميراث النبويّ', pembuat: 'اسماعيل بن يحي المزني', totalBuku: 2, sinopsis: '' },
  { no: 12, judul: 'القول السديد', tema: 'aqidah', penerbit: 'دار ابن عفّان', pembuat: 'عبد الرزاق بن عبد المحسن البرد', totalBuku: 2, sinopsis: '' },
  { no: 13, judul: 'فتح رب البرية', tema: 'aqidah', penerbit: 'مؤسسة ابن العثيمين', pembuat: 'محمد بن صالح بن محمد العثيمين', totalBuku: 2, sinopsis: '' },
  { no: 14, judul: 'مذكرة الحديث النبوية', tema: 'aqidah', penerbit: 'دار المنهاج', pembuat: 'ربيع بن هادي عُمير المدخلي', totalBuku: 2, sinopsis: '' },
  { no: 15, judul: 'تطهير الاعتقاد عن ادران الالحاد', tema: 'aqidah', penerbit: 'دار الفرقان', pembuat: 'محمد بن إسماعيل بن صلاح الصنعاني', totalBuku: 2, sinopsis: '' },
  { no: 16, judul: 'شرح الاصول الثلاثة', tema: 'aqidah', penerbit: 'دار الفرقان', pembuat: 'محمد بن عبد الوهاب بن سليمان التميمي', totalBuku: 8, sinopsis: '' },
  { no: 17, judul: 'شرح كتاب الفتن', tema: 'aqidah', penerbit: 'دار الفرقان', pembuat: '-', totalBuku: 2, sinopsis: '' },
  { no: 18, judul: 'حاشية ثلاثة الاصول', tema: 'aqidah', penerbit: '-', pembuat: 'محمد بن عبد الوهاب بن سليمان التميمي', totalBuku: 2, sinopsis: '' },
  { no: 19, judul: 'التعليقات البازية', tema: 'aqidah', penerbit: 'دار ابن عباس', pembuat: 'عبد العزيز بن عبد الله بن باز', totalBuku: 2, sinopsis: '' },
]